// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svhyuwnohckmihtsgedd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aHl1d25vaGNrbWlodHNnZWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDg0NzMsImV4cCI6MjA3MTY4NDQ3M30.wLd_U5yXYm0jl-W3WDuImyI50TYju2pQDtbdluBF0Qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});