// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhsefddtvusbrxhzsnwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpoc2VmZGR0dnVzYnJ4aHpzbndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MzkxMDUsImV4cCI6MjA3NTMxNTEwNX0.pY0GmrmHx6OKJhOloMvbcllFZ_f61MTJ4SPaDuu4WEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});